CREATE TABLE #schema_cadastrapp.sf_cnatsp (
    cnatsp character varying(5) NOT NULL,
    cnatsp_lib character varying
);

ALTER TABLE #schema_cadastrapp.sf_cnatsp OWNER TO #user_cadastrapp;

ALTER TABLE ONLY #schema_cadastrapp.sf_cnatsp
    ADD CONSTRAINT cnatsp_pkey PRIMARY KEY (cnatsp);

INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('ABREU', 'Abreuvoirs');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('ABRIC', 'Abricotiers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('ACACI', 'Acacias');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('AEROD', 'Aérodromes');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('AIRE', 'Aire ou Airial');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('ALLEE', 'Allée (no groupe)');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('ALLUV', 'Alluvions');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('AMAND', 'Amandiers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('ARDOI', 'Ardoiseries');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('ARGIL', 'Argilière');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('ASPER', 'Aspergeraie');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('AULNE', 'Aulnaie');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('AVENU', 'Avenue');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('BALLA', 'Ballastière');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('BAMBO', 'Bambouseraie');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('BASS', 'Bassins');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('BIEF', 'Bief');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('BOUL', 'Boulaie');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('BROUS', 'Broussailles ou buissons');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('BRUY', 'Bruyères');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('BTIGE', 'Verger exploite en basses tiges');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('BUIS', 'Buissière');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CAMP', 'Terrain de camping');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CANAL', 'Canal');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CASS', 'Cassis');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CEDRA', 'Cédratiers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CERCL', 'Cerclières');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CERIS', 'Cerisaie ou cerisiers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CHASS', 'Terrain de chasse');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CHAT', 'Châtaigneraie');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CHEM', 'Chemin de remembrement');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CHENE', 'Chênes');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CHLIE', 'Chênes-lièges');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CHTRU', 'Chênes truffiers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CHVER', 'Chênes verts');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CIDRE', 'Cidre');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CITRO', 'Citronniers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CLAIR', 'Claires');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('COING', 'Cognassiers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('COULE', 'Bois de couleur');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CRAY', 'Crayère');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CRESS', 'Cressonnière');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('CRYPT', 'Cryptomeria');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('DIGUE', 'Digues');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('DUNE', 'Dunes');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('EAU', 'Pièce d''eau');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('ECOLE', 'Ecole');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('EPICE', 'Epicéas');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('ESPAL', 'Verger exploite en espaliers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('ETANG', 'Etangs');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('EUCAL', 'Eucalyptus');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('FALAI', 'Falaises');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('FAMIL', 'Verger familial');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('FER', 'Chemin de fer');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('FILAO', 'Filao');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('FLOR', 'Jardin floral');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('FONT', 'Fontaine');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('FOSSE', 'Fosse');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('FOUG', 'Fougeraie');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('FRAMB', 'Framboisiers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('FRICH', 'Friche');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('GAREN', 'Garenne');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('GENET', 'Genets');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('GLAIS', 'Glaisière');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('GRAVE', 'Gravière');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('HAIES', 'Haies fruitières');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('HERB', 'Herbage');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('HETRE', 'Hêtres');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('HIST', 'Dépendances de monuments historiques');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('HORT', 'Jardins horticoles');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('HOUBL', 'Houblon');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('HTIGE', 'Vergers exploités en hautes tiges');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('HUITR', 'Parc à huîtres');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('IMM', 'Dépendances d''ensemble immobilier');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('IMPRO', 'Lande improductive');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('INTEN', 'Verger industriel');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('JARD', 'Jardin d’agrément');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('JETT', 'Jettins');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('JOUAL', 'Joualle');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('KIWIS', 'Kiwis');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('LAC', 'Lac');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('LAGUN', 'Lagune');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('LAVOI', 'Lavoir');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('LEGUM', 'Légumière de plein champ');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('MAQUI', 'Maquis');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('MARAI', 'Pré marais');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('MARAM', 'Jardin maraîcher aménagé');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('MARE', 'Mare');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('MAREC', 'Marécage');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('MARN', 'Marnière');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('MARNA', 'Jardin maraîcher non aménagé');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('MELEZ', 'Mélèzes');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('MOTTE', 'Mottes');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('MUR', 'Mûraies ou mûriers (vergers)');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('NATUR', 'Bois naturel');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('NOISE', 'Noiseraie ou noisetiers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('NOYER', 'Noyeraie ou noyers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('NPECH', 'Etang non potable');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('OLIVE', 'Olivaies ou oliviers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('ORANG', 'Orangers (vergers)');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('ORME', 'Ormaie ou ormes');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PACAG', 'Pacage');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PAFEU', 'Pare-feux');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PALMI', 'Bois palmiste');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PARC', 'Parc');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PASS', 'Passage (non groupe)');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PATIS', 'Pâtis');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PATUR', 'Pâture plantée');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PECH', 'Etangs pêchables');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PECHE', 'Pêchers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PEPIN', 'Pépinières');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PIEDS', 'Pieds-mères (vignes)');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PIERR', 'Pierraille, pierrier');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PIN', 'Pins');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PLAGE', 'Plage');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PLATR', 'Plâtrière');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PLVEN', 'Vergers de plein vent');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('POIRE', 'Poiriers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('POMME', 'Pommiers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('POTAG', 'Potagers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PROTE', 'Bois de protection');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('PRUNE', 'Pruniers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('RAIS', 'Raisins de table');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('RESER', 'Réservoir');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('RESIN', 'Résineux');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('RIVAG', 'Rivage (bois de)');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('RIZ', 'Rizière');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('ROC', 'Rocs ou rochers');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('ROUI', 'Routoir ou roussoir');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('RUE', 'Rue');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('RUINE', 'Ruines');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('SABLE', 'Sablière');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('SALIN', 'Marais salant');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('SAPIN', 'Sapins ou sapinière');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('SART', 'Sartières');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('SAULE', 'Saulaie ou saussaie');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('SERRE', 'Serre');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('SOL', 'Sols');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('SOURC', 'Source');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('SPORT', 'Terrain de sport');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('TAMAR', 'Tamarin');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('TAUZ', 'Taillis tauzin');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('TERRI', 'Terrils');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('TOURB', 'Tourbière');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('TOUYA', 'Touyas');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('VADC', 'Vins d''appellation d''origine contrôlée');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('VAGUE', 'Terrain vague');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('VANIL', 'Vanille');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('VAOC', 'Vins d''appellation d''origine contrôlée');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('VCHAS', 'Chasselas');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('VDQS', 'Vins délimités de qualité supérieure');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('VIGNE', 'Vigne');
INSERT INTO #schema_cadastrapp.sf_cnatsp VALUES ('VIVIE', 'Vivier');
