-- Create view proprietenonbatie based on Qgis Models

CREATE MATERIALIZED VIEW #schema_cadastrapp.proprietenonbatie AS 
	SELECT 
		proprietenonbatie.id_local, 
		proprietenonbatie.jdatat, 
		proprietenonbatie.comptecommunal, 
		proprietenonbatie.cgocommune,  
		proprietenonbatie.ccopre, 
		proprietenonbatie.ccosec,
		proprietenonbatie.dnupla, 
		proprietenonbatie.parcelle, 
		proprietenonbatie.ccovoi, 
		proprietenonbatie.voie, 
		proprietenonbatie.ccoriv, 
		proprietenonbatie.dnvoiri, 
		proprietenonbatie.dindic, 
		proprietenonbatie.natvoi,
		proprietenonbatie.cconvo, 
		proprietenonbatie.dvoilib,
		proprietenonbatie.dparpi, 
		proprietenonbatie.gpafpd, 
		proprietenonbatie.ccostn, 
		proprietenonbatie.ccosub, 
		proprietenonbatie.cgrnum, 
		proprietenonbatie.dsgrpf, 
		proprietenonbatie.dclssf, 
		proprietenonbatie.cnatsp, 
		proprietenonbatie.dcntsf, 
		proprietenonbatie.drcsuba, 
		proprietenonbatie.pdl, 
		proprietenonbatie.dnulot, 
		proprietenonbatie.dreflf,
		proprietenonbatie.majposa,
		proprietenonbatie.bisufad,
		proprietenonbatie.bisufad_dep,
		proprietenonbatie.bisufad_reg
	FROM dblink('host=#DBHost_qgis dbname=#DBName_qgis user=#DBUser_qgis password=#DBpasswd_qgis'::text, 
		'select 
			suf.suf as id_local,
			COALESCE(to_char(p.jdatat, ''DD/MM/YYYY''), '''') as jdatat,
			p.comptecommunal,
			p.ccodep || p.ccodir ||	p.ccocom as cgocommune,
			ltrim(p.ccopre) as ccopre,
			ltrim(p.ccosec) as ccosec,
			ltrim(p.dnupla, ''0'') as dnupla,
			p.parcelle,
			p.ccovoi,
			p.voie,
			p.ccoriv,
			ltrim(p.dnvoiri, ''0'') as dnvoiri,
			p.dindic,
			v.natvoi,
			p.cconvo,
			v.libvoi as dvoilib,
			p.dparpi,
			p.gpafpd,
			suf.ccostn,
			suf.ccosub,
			gnc.cgrnum_lib,
			sga.dsgrpf_lib,
			suf.dclssf,
			cncs.cnatsp_lib,
			suf.dcntsf,
			CAST (suf.drcsuba* 10 as integer) as drcsuba,
			suf.pdl,
			suf.dnulot,
			p.dreflf,
			CAST (suftax.c1majposa * 10 as integer) as majposa,
			CAST (suftax.c1bisufad * 10 as integer) as bisufad,
			CAST (suftax.c2bisufad * 10 as integer) as bisufad_dep,
			CAST (suftax.c3bisufad * 10 as integer) as bisufad_reg
		from #DBSchema_qgis.parcelle p
			left join #DBSchema_qgis.voie v on v.voie=p.voie
			left join #DBSchema_qgis.suf on suf.comptecommunal=p.comptecommunal and p.parcelle=suf.parcelle
			left join #DBSchema_qgis.suftaxation as suftax on suftax.suf=suf.suf
			left join #DBSchema_qgis.cgrnum as gnc on gnc.cgrnum = suf.cgrnum
			left join #DBSchema_qgis.dsgrpf as sga on sga.dsgrpf = suf.dsgrpf
			left join #DBSchema_qgis.cnatsp as cncs on cncs.cnatsp = suf.cnatsp'::text)
	proprietenonbatie(
		id_local character varying(21),  
		jdatat character varying(10),  
		comptecommunal character varying(15), 
 		cgocommune character varying(6), 
 		ccopre character varying(3),
 		ccosec character varying(2),  
 		dnupla character varying(4), 
 		parcelle character varying(19),
 		ccovoi character varying(5), 
 		voie character varying(19), 
 		ccoriv character varying(4), 
 		dnvoiri character varying(4), 
 		dindic character varying(1), 
 		natvoi character varying(4), 
 		cconvo character varying(4), 
 		dvoilib character varying(26), 
 		dparpi character varying(4), 
 		gpafpd character varying(1),
 		ccostn character varying(1), 
 		ccosub character varying(2), 
 		cgrnum character varying,
 		dsgrpf character varying, 
 		dclssf character varying(2), 
 		cnatsp character varying,
 		dcntsf integer, 
 		drcsuba integer, 
 		pdl character varying(22), 
 		dnulot character varying(7), 
 		dreflf character varying(5),
 		majposa integer,
		bisufad integer,
		bisufad_dep integer,
		bisufad_reg integer);
ALTER TABLE #schema_cadastrapp.proprietenonbatie OWNER TO #user_cadastrapp;
