-- Create view proprietaire based on Qgis Models

CREATE OR REPLACE VIEW #schema_cadastrapp.proprietaire AS 
	SELECT 
		proprietaire.id_proprietaire, 
		proprietaire.dnupro, 
		proprietaire.lot, 
		proprietaire.dnulp, 
		proprietaire.ccocif, 
		proprietaire.dnuper, 
		proprietaire.ccodro_c, 
		proprietaire.ccodem_c, 
		proprietaire.gdesip, 
		proprietaire.gtoper, 
		proprietaire.ccoqua_c, 
		proprietaire.dnatpr_c, 
		proprietaire.ccogrm_c, 
		proprietaire.dsglpm, 
		proprietaire.dforme, 
		proprietaire.ddenom, 
		proprietaire.gtyp3, 
		proprietaire.gtyp4, 
		proprietaire.gtyp5, 
		proprietaire.gtyp6, 
		proprietaire.dlign3, 
		proprietaire.dlign4, 
		proprietaire.dlign5, 
		proprietaire.dlign6, 
		proprietaire.ccopay, 
		proprietaire.ccodep1a2, 
		proprietaire.ccodira, 
		proprietaire.ccocom_adr, 
		proprietaire.ccovoi, 
		proprietaire.ccoriv, 
		proprietaire.dnvoiri, 
		proprietaire.dindic, 
		proprietaire.ccopos, 
		proprietaire.dnirpp, 
		proprietaire.dqualp, 
		proprietaire.dnomlp, 
		proprietaire.dprnlp, 
		proprietaire.jdatnss, 
		proprietaire.dldnss, 
		proprietaire.epxnee, 
		proprietaire.dnomcp, 
		proprietaire.dprncp, 
		proprietaire.dnomus,
		proprietaire.dprnus,
		proprietaire.dformjur, 
		proprietaire.dsiren, 
		proprietaire.cgocommune, 
		proprietaire.comptecommunal, 
		proprietaire.app_nom_usage,
		proprietaire.app_nom_naissance,
		prop_ccodro.ccodro, 
		prop_ccodro.ccodro_lib, 
		prop_ccoqua.ccoqua, 
		prop_ccoqua.ccoqua_lib, 
		prop_ccogrm.ccogrm, 
		prop_ccogrm.ccogrm_lib, 
		prop_ccodem.ccodem, 
		prop_ccodem.ccodem_lib, 
		prop_dnatpr.dnatpr, 
		prop_dnatpr.dnatpr_lib
	FROM dblink('host=#DBHost_qgis dbname=#DBName_qgis user=#DBUser_qgis password=#DBpasswd_qgis'::text, 
		'select 
			pqgis.proprietaire,
			pqgis.dnupro,
			pqgis.lot,
			pqgis.dnulp,
			pqgis.ccocif,
			pqgis.dnuper,
			pqgis.ccodro as ccodro_c,
			pqgis.ccodem as ccodem_c,
			pqgis.gdesip,
			pqgis.gtoper,
			pqgis.ccoqua as ccoqua_c,
			pqgis.dnatpr as dnatpr_c,
			pqgis.ccogrm as ccogrm_c,
			pqgis.dsglpm,
			pqgis.dforme,
			rtrim(pqgis.ddenom) as ddenom,
			pqgis.gtyp3,
			pqgis.gtyp4,
			pqgis.gtyp5,
			pqgis.gtyp6,
			pqgis.dlign3,
			ltrim(pqgis.dlign4, ''0'') as dlign4,
			pqgis.dlign5,
			pqgis.dlign6,
			pqgis.ccopay,
			pqgis.ccodep1a2,
			pqgis.ccodira,
			pqgis.ccocom_adr,
			pqgis.ccovoi,
			pqgis.ccoriv,
			ltrim(pqgis.dnvoiri, ''0'') as dnvoiri,
			pqgis.dindic,
			pqgis.ccopos,
			pqgis.dnirpp,
			pqgis.dqualp,
			rtrim(pqgis.dnomlp) as dnomlp,
			rtrim(pqgis.dprnlp) as dprnlp,
			rtrim(pqgis.dnomus) as dnomus,
			rtrim(pqgis.dprnus) as dprnus,
			COALESCE(to_char(pqgis.jdatnss, ''DD/MM/YYYY''), '''') as jdatnss,
			pqgis.dldnss,
			pqgis.epxnee,
			rtrim(pqgis.dnomcp) as dnomcp,
			rtrim(pqgis.dprncp) as dprncp,
			pqgis.dformjur,
			pqgis.dsiren,
			pqgis.ccodep || pqgis.ccodir || pqgis.ccocom as cgocommune,
			pqgis.comptecommunal, 
			(SELECT CASE
					WHEN gtoper = ''1'' THEN COALESCE(rtrim(dqualp),'''')||'' ''||COALESCE(rtrim(dnomus),'''')||'' ''||COALESCE(rtrim(dprnus),'''')
					WHEN gtoper = ''2'' THEN rtrim(ddenom)
				END) AS app_nom_usage,
			(SELECT CASE
					WHEN gtoper = ''1'' THEN COALESCE(rtrim(dqualp),'''')||'' ''||REPLACE(rtrim(ddenom),''/'','' '')
				END) AS app_nom_naissance
		from #DBSchema_qgis.proprietaire pqgis'::text)
	proprietaire(
		id_proprietaire character varying(20), 
		dnupro character varying(6), 
		lot character varying, 
		dnulp character varying(2), 
		ccocif character varying(4), 
		dnuper character varying(6), 
		ccodro_c character varying(1), 
		ccodem_c character varying(1), 
		gdesip character varying(1), 
		gtoper character varying(1), 
		ccoqua_c character varying(1), 
		dnatpr_c character varying(3), 
		ccogrm_c character varying(2), 
		dsglpm character varying(10), 
		dforme character varying(7), 
		ddenom character varying(60), 
		gtyp3 character varying(1), 
		gtyp4 character varying(1), 
		gtyp5 character varying(1), 
		gtyp6 character varying(1), 
		dlign3 character varying(30), 
		dlign4 character varying(36), 
		dlign5 character varying(30), 
		dlign6 character varying(32), 
		ccopay character varying(3), 
		ccodep1a2 character varying(2), 
		ccodira character varying(1), 
		ccocom_adr character varying(3), 
		ccovoi character varying(5), 
		ccoriv character varying(4), 
		dnvoiri character varying(4),
		dindic character varying(1), 
		ccopos character varying(5), 
		dnirpp character varying(10), 
		dqualp character varying(3), 
		dnomlp character varying(30), 
		dprnlp character varying(15), 
		jdatnss character varying(10), 
		dldnss character varying(58), 
		epxnee character varying(3), 
		dnomcp character varying(30), 
		dprncp character varying(15), 
		dnomus character varying(60),
		dprnus character varying(40),
		dformjur character varying(4), 
		dsiren character varying(10),
		cgocommune character varying(6), 
		app_nom_usage character varying(120),
		app_nom_naissance character varying(70))
	LEFT JOIN #schema_cadastrapp.prop_ccodro ON proprietaire.ccodro_c::text = prop_ccodro.ccodro::text
	LEFT JOIN #schema_cadastrapp.prop_ccoqua ON proprietaire.ccoqua_c::text = prop_ccoqua.ccoqua::text
	LEFT JOIN #schema_cadastrapp.prop_ccogrm ON proprietaire.ccogrm_c::text = prop_ccogrm.ccogrm::text
	LEFT JOIN #schema_cadastrapp.prop_ccodem ON proprietaire.ccodem_c::text = prop_ccodem.ccodem::text
	LEFT JOIN #schema_cadastrapp.prop_dnatpr ON proprietaire.dnatpr_c::text = prop_dnatpr.dnatpr::text;

ALTER TABLE #schema_cadastrapp.proprietaire OWNER TO #user_cadastrapp;


